; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4  ; Windows
;upload_port = /dev/ttyUSB1 ; Linux

build_flags =
    -I include
    -std=gnu++2a

build_src_flags =
    -Wall
    -Wextra
    -Werror
    -Wshadow
    -Wconversion
    -Wsign-conversion
    -Wnull-dereference
    -Wno-error=conversion
    -Wno-error=sign-conversion

; Downloaded automatically and stored per-project.
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    knolleary/PubSubClient@^2.8
