"""MQTT topics consumed by the IAQ ingestion service."""

from collections import namedtuple

Subscription = namedtuple("Subscription", ["topic", "qos"])

PREFIX = "iaq"
MAC_PLACEHOLDER = "+"
SENSOR_DATA_TOPIC_SUFFIX = "sensor_data"
SENSOR_INFO_TOPIC_SUFFIX = "sensor_info"
DEVICE_HEALTH_TOPIC_SUFFIX = "device_health"
DEVICE_INFO_TOPIC_SUFFIX = "device_info"
DEVICE_STATUS_TOPIC_SUFFIX = "device_status"
CLAIM_REQUEST_TOPIC_SUFFIX = "claim_request"
COMMAND_TOPIC_SUFFIX = "command"
SENSOR_TOPIC_SUFFIX = "sensor"
CLAIM_STATUS_TOPIC_SUFFIX = "claim_status"

SENSOR_DATA_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{SENSOR_DATA_TOPIC_SUFFIX}"
SENSOR_INFO_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{SENSOR_INFO_TOPIC_SUFFIX}"
DEVICE_HEALTH_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{DEVICE_HEALTH_TOPIC_SUFFIX}"
DEVICE_INFO_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{DEVICE_INFO_TOPIC_SUFFIX}"
DEVICE_STATUS_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{DEVICE_STATUS_TOPIC_SUFFIX}"
CLAIM_REQUEST_TOPIC = f"{PREFIX}/{MAC_PLACEHOLDER}/{CLAIM_REQUEST_TOPIC_SUFFIX}"


def create_topic(mac: str, topic_suffix: str) -> str:
    return f"{PREFIX}/{mac}/{topic_suffix}"


QOS_LEVEL = 1

SUBSCRIPTIONS = [
    Subscription(SENSOR_DATA_TOPIC, QOS_LEVEL),
    Subscription(SENSOR_INFO_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_HEALTH_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_INFO_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_STATUS_TOPIC, QOS_LEVEL),
    Subscription(CLAIM_REQUEST_TOPIC, QOS_LEVEL),
]
