"""MQTT topics consumed by the IAQ ingestion service."""

from collections import namedtuple

Subscription = namedtuple("Subscription", ["topic", "qos"])

PREFIX = "iaq/+/"
SENSOR_DATA_TOPIC_SUFFIX = "sensor_data"
SENSOR_INFO_TOPIC_SUFFIX = "sensor_info"
DEVICE_HEALTH_TOPIC_SUFFIX = "device_health"
DEVICE_INFO_TOPIC_SUFFIX = "device_info"
DEVICE_STATUS_TOPIC_SUFFIX = "device_status"

SENSOR_DATA_TOPIC = f"{PREFIX}{SENSOR_DATA_TOPIC_SUFFIX}"
SENSOR_INFO_TOPIC = f"{PREFIX}{SENSOR_INFO_TOPIC_SUFFIX}"
DEVICE_HEALTH_TOPIC = f"{PREFIX}{DEVICE_HEALTH_TOPIC_SUFFIX}"
DEVICE_INFO_TOPIC = f"{PREFIX}{DEVICE_INFO_TOPIC_SUFFIX}"
DEVICE_STATUS_TOPIC = f"{PREFIX}{DEVICE_STATUS_TOPIC_SUFFIX}"

QOS_LEVEL = 1

SUBSCRIPTIONS = [
    Subscription(SENSOR_DATA_TOPIC, QOS_LEVEL),
    Subscription(SENSOR_INFO_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_HEALTH_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_INFO_TOPIC, QOS_LEVEL),
    Subscription(DEVICE_STATUS_TOPIC, QOS_LEVEL),
]
