# Generated by Django 6.0.6 on 2026-07-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HealthReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.SmallIntegerField()),
                ('uptime', models.PositiveIntegerField()),
                ('heap', models.PositiveIntegerField()),
                ('min_heap', models.PositiveIntegerField()),
                ('firmware_version', models.CharField(max_length=40)),
                ('reset_reason', models.SmallIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_readings', to='iaq.device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaq', models.FloatField()),
                ('co2_equivalent', models.FloatField()),
                ('voc_equivalent', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('accuracy', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='iaq.device')),
            ],
        ),
    ]
