# Generated by Django 6.0.6 on 2026-07-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0002_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iaq.sensorreading'),
        ),
    ]
