# Generated by Django 6.0.6 on 2026-07-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0003_device_latest_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreading',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='healthreading',
            name='reset_reason',
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_health', to='iaq.device'),
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_version', models.CharField(max_length=40)),
                ('chip_model', models.CharField(max_length=40)),
                ('chip_revision', models.PositiveSmallIntegerField()),
                ('chip_cores', models.PositiveSmallIntegerField()),
                ('reset_reason', models.SmallIntegerField(default=0)),
                ('total_heap', models.PositiveIntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to='iaq.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='iaq.device')),
            ],
        ),
    ]
