# Generated by Django 6.0.6 on 2026-07-20 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0004_remove_healthreading_firmware_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreading',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 10, 38, 2, 991673, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
