# Generated by Django 6.0.6 on 2026-08-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0005_healthreading_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='latest_reading',
            new_name='latest_sensor_reading',
        ),
        migrations.AddField(
            model_name='device',
            name='latest_health_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iaq.healthreading'),
        ),
    ]
