# Generated by Django 6.0.6 on 2026-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0006_rename_latest_reading_device_latest_sensor_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='sensor_mode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
