# Generated by Django 6.0.6 on 2026-08-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0006_rename_latest_reading_device_latest_sensor_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_info', to='iaq.device')),
            ],
        ),
    ]
