# Generated by Django 6.0.6 on 2026-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0007_deviceinfo_sensor_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='chip_cores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='chip_model',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='chip_revision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='firmware_version',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='total_heap',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
