# Generated by Django 6.0.6 on 2026-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0008_alter_deviceinfo_chip_cores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('claim_code', models.CharField(max_length=6)),
            ],
        ),
    ]
