# Generated by Django 6.0.6 on 2026-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0008_alter_deviceinfo_chip_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='claim_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
