# Generated by Django 6.0.6 on 2026-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaq', '0009_deviceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceclaim',
            name='claim_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
