name: PlatformIO Dependabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: run PlatformIO Dependabot
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: peterus/platformio_dependabot@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: iot-esp32-iaq-app
